[book]
title = "Rust性能优化"
authors = ["Nicholas Nethercote"]
src = "src"
language = "zh"
multilingual = false

[build]
create-missing = false

[rust]
edition = "2018"

[output.html]
curly-quotes = true
default-theme = "rust"
git-repository-url = "https://github.com/poly000/perf-book-zh"
site-url = "https://poly000.github.io/perf-book-zh/"
